#!/bin/bash
# One-click install: run from project root after uploading (e.g. cd /root/beard-shop && bash install.sh)
# Usage: bash install.sh   (or: bash <(curl -s https://raw.githubusercontent.com/.../install.sh) if hosted on GitHub)

set -e
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo "========================================"
echo "  Beard Brand Collective - One-Click Deploy"
echo "========================================"

# 1. Install Docker if not present
if ! command -v docker &>/dev/null; then
  echo "[1/4] Installing Docker..."
  apt-get update -qq
  apt-get install -y -qq ca-certificates curl
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  chmod a+r /etc/apt/keyrings/docker.asc
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "${VERSION_CODENAME:-$(. /etc/os-release && echo "$VERSION_CODENAME")}") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  apt-get update -qq
  apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
else
  echo "[1/4] Docker already installed."
fi

# 2. Generate random ADMIN_PATH (alphanumeric only) and main account (skip if .env exists)
if [ -f .env ]; then
  echo "[2/4] .env exists, keeping it."
  export $(grep -v '^#' .env | xargs)
else
  # Full random alphanumeric (no fixed prefix)
  ADMIN_PATH="/$(LC_ALL=C tr -dc 'a-zA-Z0-9' < /dev/urandom 2>/dev/null | head -c 20)"
  [ -z "$ADMIN_PATH" ] && ADMIN_PATH="/$(openssl rand -hex 10)"
  INIT_ADMIN_USER="$(LC_ALL=C tr -dc 'a-zA-Z0-9' < /dev/urandom 2>/dev/null | head -c 10)"
  [ -z "$INIT_ADMIN_USER" ] && INIT_ADMIN_USER="admin$(openssl rand -hex 4)"
  INIT_ADMIN_PASS="$(LC_ALL=C tr -dc 'a-zA-Z0-9' < /dev/urandom 2>/dev/null | head -c 14)"
  [ -z "$INIT_ADMIN_PASS" ] && INIT_ADMIN_PASS="$(openssl rand -hex 7)"
  echo "[2/4] Writing .env with random ADMIN_PATH and main account"
  cat > .env << EOF
# Generated by install.sh - save these credentials
ADMIN_PATH=${ADMIN_PATH}
INIT_ADMIN_USER=${INIT_ADMIN_USER}
INIT_ADMIN_PASS=${INIT_ADMIN_PASS}
PORT=3001
NODE_ENV=production
DB_PATH=/app/data/database.sqlite
ALLOWED_ORIGINS=
EOF
fi

# 3. Docker Compose build and run (full stack: frontend + backend on same server)
echo "[3/4] Building and starting containers (frontend + backend)..."
[ -f .env ] && export $(grep -v '^#' .env | xargs)
docker compose -f docker-compose.full.yml up -d --build

# 4. Output access info (do not echo password to avoid shell history / CI log leakage)
echo "[4/4] Done."
SERVER_IP=$(curl -s --max-time 2 https://api.ipify.org 2>/dev/null || hostname -I 2>/dev/null | awk '{print $1}' || echo "YOUR_SERVER_IP")
[ -f .env ] && export $(grep -v '^#' .env | xargs)
echo ""
echo "========================================"
echo "   Deployment complete!"
echo "   API:      http://${SERVER_IP}/api/"
echo "   Admin:    http://${SERVER_IP}${ADMIN_PATH}"
echo "   Store:    No IP entry. Add a domain in Admin -> Shop Management, then resolve that domain to this server."
echo "   Main account credentials are in .env (INIT_ADMIN_USER, INIT_ADMIN_PASS)."
echo "   Open .env to view; change password in Account Management after first login."
echo "========================================"
